// <auto-generated />
namespace Application.bbdd.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Entidadgastos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Entidadgastos));
        
        string IMigrationMetadata.Id
        {
            get { return "201905041433436_Entidad gastos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
